### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by aerith1984** [odukjung/Card-Switch-Rework#1]
I HAVE NEW OPCODES..EVEN BFR PATCH THE MOD WASNT WORKING..NOT CHANGING PRESETS..I HAVE 10 TABS ALL SET

**Comment by odukjung** [comment]
go download again

**Comment by aerith1984** [comment]
works only issue is when i m in open world preset is not going to 10 and is using mm card preset not phoenix

**Comment by odukjung** [comment]
this mod for DG > open world

**Comment by aerith1984** [comment]
when u go to bahhar 2nd phase the mod switches to rk extreme
